#!/usr/bin/env sh

source_dir="twp"
output_dir="figleaf"
index="source_modules.txt"

rm .figleaf
figleaf --ignore-pylibs `which py.test`

find "$source_dir/" -name "*.py" > $index
rm -rf $output_dir
figleaf2html --output-directory="$output_dir" --files-list="$index"
