#!/usr/bin/env python

"""
TiddlyWebWiki dev instantiation
"""

import sys
import os

import tiddlywebplugins.devstore as devstore

from tiddlywebplugins.instancer.util import spawn

from tiddlywebwiki import instance as instance_module
from tiddlywebwiki.config import config as init_config


def main(args):
    args = [unicode(arg, 'utf-8') for arg in args]
    instance_path = args[1]

    instance_tiddlers = init_config["instance_tiddlers"]
    for pair in args[2:]:
        bag, filepath = pair.split(':', 1)
        filepath = os.path.abspath(filepath)

        # XXX: _pretty_print doesn't handle Unicode strings properly
        bag = bag.encode('utf-8')
        filepath = filepath.encode('utf-8')

        try:
            instance_tiddlers[bag].append(filepath)
        except KeyError:
            instance_tiddlers[bag] = [filepath]

    server_store = ['tiddlywebplugins.devstore', { 'store_root': 'store' }]
    init_config['server_store'] = server_store
    custom_config = {
        'server_store': server_store,
        'local_instance_tiddlers': instance_tiddlers,
        'log_level': 'DEBUG'
    }
    instance_module.instance_config.update(custom_config)

    # prevent local tiddlers from being created in the devstore
    devstore.Store.tiddler_put = lambda self, tiddler: None

    spawn(instance_path, init_config, instance_module)
    return True


if __name__ == '__main__':
    status = not main(sys.argv)
    sys.exit(status)
